In [1]:
import numpy as np

In [3]:
matriz = np.array([[3,4,2],[6,1,5],[7,9,8]])
matriz

array([[3, 4, 2],
       [6, 1, 5],
       [7, 9, 8]])

In [4]:
det = np.linalg.det(matriz)
det

-68.99999999999996

In [31]:
A = np.random.randint(0, 10, size=(4,4))
A

array([[6, 7, 3, 8],
       [5, 6, 5, 8],
       [2, 6, 5, 3],
       [8, 8, 7, 4]])

In [9]:
np.linalg.det(A)

184.99999999999991

In [45]:
A = np.array([[3,4,2],[6,1,5],[7,9,8]])
B = np.array([10, 2 , 6])

In [34]:
A

array([[3, 4, 2],
       [6, 1, 5],
       [7, 9, 8]])

In [46]:
B

array([10,  2,  6])

In [47]:
A_inv = np.linalg.inv(A)
A_inv

array([[ 0.53623188,  0.20289855, -0.26086957],
       [ 0.1884058 , -0.14492754,  0.04347826],
       [-0.68115942, -0.01449275,  0.30434783]])

In [48]:
x = np.dot(A_inv, B)
x

array([ 4.20289855,  1.85507246, -5.01449275])

In [50]:
x_solve = np.linalg.solve(A,B)

array([ 4.20289855,  1.85507246, -5.01449275])