In [1]:
matriz_A = [[1,2,3], [4,5,6]]

In [2]:
matriz_A

[[1, 2, 3], [4, 5, 6]]

In [5]:
import numpy as np
matriz_B = np.array([[1,2,3], [4,5,6],[7,8,9]])

In [4]:
matriz_B

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
matriz_B [0][0]


1

In [9]:
matriz_B [0]


array([1, 2, 3])

In [10]:
matriz_B [1]


array([4, 5, 6])

In [13]:
matriz_B [2]

array([7, 8, 9])

In [15]:
matriz_transposta = matriz_B.transpose()

In [17]:
matriz_transposta

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [19]:
matriz_B + matriz_transposta

array([[ 2,  6, 10],
       [ 6, 10, 14],
       [10, 14, 18]])

In [20]:
matriz_B - matriz_transposta

array([[ 0, -2, -4],
       [ 2,  0, -2],
       [ 4,  2,  0]])

In [22]:
np.dot(matriz_B, matriz_transposta)

array([[ 14,  32,  50],
       [ 32,  77, 122],
       [ 50, 122, 194]])