In [1]:
import numpy as np


In [17]:
matriz_A = np.array([[10, 2 , 6],[ 7, 10, 11],[12, 18, 10]])
matriz_A

array([[10,  2,  6],
       [ 7, 10, 11],
       [12, 18, 10]])

In [18]:
matriz_transposta = matriz_A.transpose()
matriz_transposta

array([[10,  7, 12],
       [ 2, 10, 18],
       [ 6, 11, 10]])

In [19]:
np.linalg.det(matriz_A)

-820.0000000000003

In [29]:
inversa = np.linalg.inv(matriz_A)
inversa

array([[ 0.1195122 , -0.10731707,  0.04634146],
       [-0.07560976, -0.03414634,  0.08292683],
       [-0.00731707,  0.1902439 , -0.10487805]])

In [32]:
np.dot(matriz_A, inversa)

array([[ 1.00000000e+00, -2.77555756e-16,  1.38777878e-16],
       [ 1.50053581e-16,  1.00000000e+00,  1.80411242e-16],
       [ 5.20417043e-18,  5.55111512e-17,  1.00000000e+00]])

In [35]:
B = np.array([[1,-2],[0,1]])
B

array([[ 1, -2],
       [ 0,  1]])

In [37]:
inv_B = np.linalg.inv(B)
inv_B

array([[1., 2.],
       [0., 1.]])

In [39]:
np.dot(B, inv_B)

array([[1., 0.],
       [0., 1.]])

In [42]:
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])